;==================================================================
;===============  Configuracoes Gerais do Serviço =================
;==================================================================
[GENERAL]
CONSOLELOG=1
;==================================================================
;====================  Configuracoes de Conexão ===================
;==================================================================
[BALANCE_HTTP]
;Comando para criar serviço: -balance_http -i 

LOCAL_SERVER_PORT = 8186
REMOTE_SERVER_01 = LOCALHOST 4085

; Servidores Extras que vão ser monitorados
N_EXTRA_SERVERS = 1
EXTRA_SERVER_000 = LOCALHOST 9021

;==================================================================
;====================  Configuracoes do Serviço ===================
;==================================================================
SERVICE_NAME = 22.00-Protheus12_broker_web_HML
SERVICE_DISPLAY_NAME = "22.00 - TOTVS HML | Appserver 12 - Broker Web"

;==================================================================
;================ Configurações de HTTPS com o web ================
;==================================================================
SSL_ENCRYPT_UPSTREAM = 1

SSL_METHOD=SSL/TLS
SSL_CERTIFICATE=C:\TOTVS\TOTVS12\ERP\PROTHEUS12_HML\bin\Appserver_Broker_Web\totvs_certificate.crt
SSL_KEY=C:\TOTVS\TOTVS12\ERP\PROTHEUS12_HML\bin\Appserver_Broker_Web\totvs_certificate_key.pem
SSL_PASSPHRASE=

;==================================================================
;========================= Web Monitor  ===========================
;==================================================================
USING_WEBMONITOR = 1

[MONITOR]
SourcePath=C:\TOTVS\TOTVS12\ERP\PROTHEUS12_HML\apos\apo_principal
RPOCustom=C:\TOTVS\TOTVS12\ERP\PROTHEUS12_HML\apos\apo_principal\Customizados_Beplast.rpo
RootPath=C:\TOTVS\TOTVS12\ERP\PROTHEUS12_HML\Protheus_Data
StartPath=\system\
RPODB=TOP
RPOVERSION=120
DBDataBase=MSSQL
DBAlias=PROTHEUS12_HOMOLOGACAO
DBServer=10.101.30.40
DBPort=7999