;==================================================================
;==================  Configuracoes do Environment PRODUCAO ========
;==================================================================
[PROTHEUS]
SourcePath=D:\TOTVS\Protheus\protheus\apos\apo_principal
RpoCustom=D:\TOTVS\Protheus\protheus\apos\apo_principal\custom.rpo
RootPath=D:\TOTVS\Protheus\protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoLanguage=multi
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
StartSysInDB=1
topmemomega=50
DBDataBase=POSTGRES
DBAlias=protheusPG
DBServer=localhost
DBPort=7890
DbODBCDriver=PostgreSQL ODBC Driver(ANSI)
DbDNSServer=localhost
;theme=sunset

;==================================================================
;=======  Configuracoes do Rede e Autenticacao do Serviço =========
;==================================================================
[Drivers]
Active=TCP
MULTIPROTOCOLPORT=1
MULTIPROTOCOLPORTSECURE=1

[TCP]
TYPE=TCPIP
Port=4085

;==================================================================
;===============  Configuracoes Gerais do Serviço =================
;==================================================================
[General]
CONSOLE=1
CONSOLELOG=1
LogHttpFuncs=1
tlpp_rest_log=1
Maxquerysize=31960
;inactiveTimeout=3600
App_Environment=PROTHEUS

;==================================================================
;====================  Configuracoes do Serviço ===================
;=================================================================
[Service]
Name=03.01-TOTVS-Appserver12
DisplayName=03.01 - TOTVS | Appserver 12 - Broker Web Slave 01

[LICENSECLIENT]
server=localhost
port=5555

;==================================================================
;======================  Configuracoes do WebApp ==================
;==================================================================
[WEBAPP]
Port=8188
HideParamsForm=0
EnvServer=PROTHEUS
LastMainProg=SIGAMDI
[WebApp/webapp]
MPP=

[WEBMONITOR]
Debug=0

;==================================================================
;=================== Configuracoes do WebWebAgent =================
;==================================================================

[WEBAGENT]
VERSION=1.0.16
Port=9696
Windows_x86=D:\TOTVS\Protheus\Protheus\bin\WebAgent\web-agent-1.0.16-RC3-windows-x86-release.setup.exe
Windows_x64=D:\TOTVS\Protheus\Protheus\bin\WebAgent\web-agent-1.0.16-RC3-windows-x64-release.setup.exe
Darwin_universal=D:\TOTVS\Protheus\Protheus\bin\WebAgent\web-agent-1.0.16-RC3-darwin-universal-release.dmg