;==================================================================
;==================  Configuracoes do Environment PRODUCAO ========
;==================================================================
[PROTHEUS]
SourcePath=D:\TOTVS\Protheus\protheus\apos\apo_principal
RpoCustom=D:\TOTVS\Protheus\protheus\apos\apo_principal\custom.rpo
RootPath=D:\TOTVS\Protheus\protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoLanguage=multi
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
StartSysInDB=1
topmemomega=50
DBDataBase=POSTGRES
DBAlias=protheusPG
DBServer=localhost
DBPort=7890
DbODBCDriver=PostgreSQL ODBC Driver(ANSI)
DbDNSServer=localhost

;==================================================================
;=======  Configuracoes do Rede e Autenticacao do Serviço =========
;==================================================================
[Drivers]
Active=TCP
MULTIPROTOCOLPORT=1
MULTIPROTOCOLPORTSECURE=0

[TCP]
TYPE=TCPIP
Port=4090

;==================================================================
;===============  Configuracoes Gerais do Serviço =================
;==================================================================
[General]
CONSOLE=1
CONSOLELOG=1
LogHttpFuncs=1
tlpp_rest_log=1
Maxquerysize=31960
;inactiveTimeout=3600
App_Environment=PROTHEUS

;==================================================================
;====================  Configuracoes do Serviço ===================
;=================================================================
[Service]
Name=05.00-schedule
DisplayName=05.00 - TOTVS | Appserver 12 - Schedule

[LICENSECLIENT]
server=localhost
port=5555

;==================================================================
;===============  Configuracoes do Web App exclusivo ==============
;==================================================================
[WebApp/webapp]
MPP=